services:
  api:
    build:
      context: .
      dockerfile: ./host/api/Dockerfile
    volumes:
      - ./api:/var/www/html
      - ./.env:/var/www/html/.env
      - ./tests:/var/www/html/tests
      - ./phpunit.xml:/var/www/html/phpunit.xml
    ports:
      - "80"
    depends_on:
      - db
    restart: always
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./host/mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
  nginx-balancer:
    image: nginx:latest
    volumes:
      - ./host/nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "4000:4000"
    restart: always
  web:
    build:
      context: .
      dockerfile: ./host/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    # Links the PHPMyAdmin service to the MySQL database service
      - db 
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db
      # Use MySQL root password for PHPMyAdmin
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db